
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - database
      - cache

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - app_network

  cache:
    image: redis:7
    networks:
      - app_network

  proxy:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - app_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ci-cd:
    build:
      context: ./ci-cd
      dockerfile: Dockerfile
    networks:
      - app_network

networks:
  app_network:
    driver: overlay

volumes:
  database_data:
